---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: jammy-tiny
spec:
  id: "io.buildpacks.stacks.jammy.tiny"
  buildImage:
    image: paketobuildpacks/build-jammy-tiny
  runImage:
    image: paketobuildpacks/run-jammy-tiny
