---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: jammy-tiny
spec:
  id: "io.buildpacks.stacks.jammy.tiny"
  buildImage:
    image: paketobuildpacks/build-jammy-tiny:0.1.69
  runImage:
    image: paketobuildpacks/run-jammy-tiny:0.1.69

---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: jammy-base
spec:
  id: "io.buildpacks.stacks.jammy"
  buildImage:
    image: paketobuildpacks/build-jammy-base:0.1.67
  runImage:
    image: paketobuildpacks/run-jammy-base:0.1.67
