---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: jammy-full
spec:
  id: "io.buildpacks.stacks.jammy"
  buildImage:
    image: paketobuildpacks/build-jammy-full
  runImage:
    image: paketobuildpacks/run-jammy-full
