#@ load("@ytt:data", "data")
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default
spec:
  sources:
    - image: gcr.io/paketo-buildpacks/java:9.1.0
    - image: gcr.io/paketo-buildpacks/java-native-image:8.0.0
    - image: gcr.io/paketo-buildpacks/procfile:5.6.0
    - image: gcr.io/paketo-buildpacks/go:4.3.1
    - image: gcr.io/paketo-buildpacks/python:2.9.1
    - image: gcr.io/paketo-buildpacks/nodejs:1.5.1
    - image: gcr.io/paketo-buildpacks/dotnet-core:0.35.0
    - image: gcr.io/paketo-buildpacks/web-servers:0.11.1
    - image: gcr.io/paketo-buildpacks/ruby:0.31.0
    - image: gcr.io/paketo-buildpacks/opentelemetry:1.0.0
