#@ load("@ytt:data", "data")
---
apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: default
spec:
  serviceAccountRef:
    name: kp-default-repository-serviceaccount
    namespace: kpack
  tag: #@ "{}:clusterbuilder-{}".format(data.values.kp_default_repository.name, "default")
  stack:
    name: jammy-base
    kind: ClusterStack
  order:
    - group:
        - id: paketo-buildpacks/ruby
    - group:
        - id: paketo-buildpacks/dotnet-core
    - group:
        - id: paketo-buildpacks/go
    - group:
        - id: paketo-buildpacks/graalvm
    - group:
        - id: paketo-buildpacks/java-native-image
    - group:
        - id: paketo-buildpacks/java
    - group:
        - id: paketo-buildpacks/opentelemetry
    - group:
        - id: paketo-buildpacks/web-servers
    - group:
        - id: paketo-buildpacks/nodejs
    - group:
        - id: paketo-buildpacks/python
    - group:
        - id: paketo-buildpacks/procfile
