#@ load("@ytt:data", "data")
---
apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: jammy-tiny
spec:
  serviceAccountRef:
    name: kp-default-repository-serviceaccount
    namespace: kpack
  tag: #@ "{}:clusterbuilder-{}".format(data.values.kp_default_repository.name, "jammy-tiny")
  stack:
    name: jammy-tiny
    kind: ClusterStack
  order:
    - group:
        - id: paketo-buildpacks/graalvm
    - group:
        - id: paketo-buildpacks/java-native-image
    - group:
        - id: paketo-buildpacks/java
    - group:
        - id: paketo-buildpacks/opentelemetry
    - group:
        - id: paketo-buildpacks/go
    - group:
        - id: paketo-buildpacks/procfile
